language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - "dataApp/node_modules"

branches:
  only:
    - master

install:
  - yarn install
  - yarn generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: dataApp/dist
  on:
    branch: master
